//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    
    using System;
    using System.Collections.Generic;
    
    [System.Runtime.Serialization.DataContract]
    public partial class Currency
    {
        public Currency()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        [System.Runtime.Serialization.DataMember]public int CurrencyID { get; set; }
        [System.Runtime.Serialization.DataMember]public string Name { get; set; }
    
        [System.Runtime.Serialization.DataMember]public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
