//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    
    using System;
    using System.Collections.Generic;
    
    [System.Runtime.Serialization.DataContract]
    public partial class ErrorLog
    {
        [System.Runtime.Serialization.DataMember]public long ErrorLogID { get; set; }
        [System.Runtime.Serialization.DataMember]public string ProgramName { get; set; }
        [System.Runtime.Serialization.DataMember]public string MethodName { get; set; }
        [System.Runtime.Serialization.DataMember]public string UserName { get; set; }
        [System.Runtime.Serialization.DataMember]public string ComputerName { get; set; }
        [System.Runtime.Serialization.DataMember]public System.DateTime DateCreated { get; set; }
        [System.Runtime.Serialization.DataMember]public string ErrorMessage { get; set; }
    }
}
